"""initial_schema

Revision ID: 0d23202f2755
Revises: 
Create Date: 2026-04-18 15:26:14.996322+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d23202f2755'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('msp_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defectdojo_product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['msp_id'], ['tenants.id'], name=op.f('fk_tenants_msp_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_custom_domain'), 'tenants', ['custom_domain'], unique=True)
    op.create_index(op.f('ix_tenants_defectdojo_product_id'), 'tenants', ['defectdojo_product_id'], unique=False)
    op.create_index(op.f('ix_tenants_msp_id'), 'tenants', ['msp_id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('assets',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('external_domain', 'external_ip', 'internal_endpoint', name='asset_type'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('wazuh_agent_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('tenant_id', 'value', name='uq_assets_tenant_id_value')
    )
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('platform_admin', 'msp_admin', 'msp_technician', 'customer_readonly', name='user_role'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('scan_type', postgresql.ENUM('external_full', 'web_app', 'internal', 'fast', name='scan_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'running', 'completed', 'failed', 'cancelled', name='scan_status'), server_default='queued', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('defectdojo_engagement_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_scan_jobs_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scan_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs'))
    )
    op.create_index(op.f('ix_scan_jobs_asset_id'), 'scan_jobs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_defectdojo_engagement_id'), 'scan_jobs', ['defectdojo_engagement_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scan_jobs_tenant_id'), 'scan_jobs', ['tenant_id'], unique=False)
    op.create_table('findings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('severity', postgresql.ENUM('critical', 'high', 'medium', 'low', 'info', name='finding_severity'), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'resolved', 'accepted', 'false_positive', name='finding_status'), server_default='open', nullable=False),
    sa.Column('source', postgresql.ENUM('openvas', 'zap', 'nuclei', 'wazuh', 'hibp', 'manual', name='finding_source'), nullable=False),
    sa.Column('cvss_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('epss_score', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('epss_percentile', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('defectdojo_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_findings_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_findings_scan_job_id_scan_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_findings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_cve_id'), 'findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_findings_defectdojo_id'), 'findings', ['defectdojo_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_job_id'), 'findings', ['scan_job_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_index('ix_findings_tenant_id_status_severity', 'findings', ['tenant_id', 'status', 'severity'], unique=False)
    op.create_table('ratings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=False),
    sa.Column('overall_grade', postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'F', name='rating_grade'), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('patch_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('network_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('web_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('endpoint_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('email_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('breach_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ransomware_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_ratings_scan_job_id_scan_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ratings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('scan_job_id', name=op.f('uq_ratings_scan_job_id'))
    )
    op.create_index(op.f('ix_ratings_overall_grade'), 'ratings', ['overall_grade'], unique=False)
    op.create_index(op.f('ix_ratings_tenant_id'), 'ratings', ['tenant_id'], unique=False)
    op.create_table('reports',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=True),
    sa.Column('type', postgresql.ENUM('executive', 'technical', name='report_type'), nullable=False),
    sa.Column('pdf_data', sa.LargeBinary(), nullable=False),
    sa.Column('pdf_size_bytes', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], name=op.f('fk_reports_generated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_reports_scan_job_id_scan_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_reports_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_scan_job_id'), 'reports', ['scan_job_id'], unique=False)
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reports_type'), 'reports', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_scan_job_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_ratings_tenant_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_overall_grade'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('ix_findings_tenant_id_status_severity', table_name='findings')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_job_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_defectdojo_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scan_jobs_tenant_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_defectdojo_engagement_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_asset_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_msp_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_defectdojo_product_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_custom_domain'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###

    # Alembic autogenerate does not drop ENUM types — they persist after
    # their tables are gone and then re-running `upgrade` errors with
    # "type already exists". Drop them explicitly so downgrade/upgrade
    # cycles are idempotent.
    for enum_name in (
        'report_type',
        'rating_grade',
        'finding_source',
        'finding_status',
        'finding_severity',
        'scan_status',
        'scan_type',
        'asset_type',
        'user_role',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
