"""add_tenant_domain_verification

Revision ID: 20d5585c2855
Revises: d98ae26fba01
Create Date: 2026-04-18 16:01:34.448887+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d5585c2855'
down_revision: str | None = 'd98ae26fba01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('custom_domain_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenants', sa.Column('custom_domain_verification_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'custom_domain_verification_token')
    op.drop_column('tenants', 'custom_domain_verified')
    # ### end Alembic commands ###
