"""add_scan_schedules_table

Revision ID: 88cbca709c5a
Revises: 20d5585c2855
Create Date: 2026-04-18 16:12:38.225138+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88cbca709c5a'
down_revision: str | None = '20d5585c2855'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_schedules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    # `scan_type` enum already exists from the initial migration — create_type=False.
    sa.Column(
        'scan_type',
        postgresql.ENUM(
            'external_full', 'web_app', 'internal', 'fast',
            name='scan_type',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('cron_expression', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('blackout_start', sa.Time(), nullable=True),
    sa.Column('blackout_end', sa.Time(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_scan_schedules_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scan_schedules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_schedules'))
    )
    op.create_index(op.f('ix_scan_schedules_asset_id'), 'scan_schedules', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scan_schedules_next_run_at'), 'scan_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_scan_schedules_tenant_id'), 'scan_schedules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_schedules_tenant_id'), table_name='scan_schedules')
    op.drop_index(op.f('ix_scan_schedules_next_run_at'), table_name='scan_schedules')
    op.drop_index(op.f('ix_scan_schedules_asset_id'), table_name='scan_schedules')
    op.drop_table('scan_schedules')
    # ### end Alembic commands ###
