"""add_finding_ninjaone_ticket_id

Revision ID: d98ae26fba01
Revises: 23b19d198859
Create Date: 2026-04-18 15:51:42.272962+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98ae26fba01'
down_revision: str | None = '23b19d198859'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('ninjaone_ticket_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_findings_ninjaone_ticket_id'), 'findings', ['ninjaone_ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_ninjaone_ticket_id'), table_name='findings')
    op.drop_column('findings', 'ninjaone_ticket_id')
    # ### end Alembic commands ###
