"""add_user_invitation_columns

Revision ID: 23b19d198859
Revises: 0d23202f2755
Create Date: 2026-04-18 15:43:50.156125+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b19d198859'
down_revision: str | None = '0d23202f2755'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invitation_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('invitation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_invitation_token'), 'users', ['invitation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invitation_token'), table_name='users')
    op.drop_column('users', 'invitation_expires_at')
    op.drop_column('users', 'invitation_token')
    # ### end Alembic commands ###
