"""SQLAlchemy declarative base + shared mixins.

All ORM models inherit from `Base` and use the mixins to get UUID PKs and
timestamp columns consistently. Enums are defined alongside their models.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum as PyEnum
from typing import TypeVar
from uuid import UUID, uuid4

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

_E = TypeVar("_E", bound=PyEnum)


def pg_enum(enum_class: type[_E], *, name: str) -> PG_ENUM:
    """PG ENUM that stores `.value` strings (lowercase) instead of `.name` (UPPER).

    SQLAlchemy's default for Python enums is `.name`, which doesn't match the
    `.value` used everywhere else in the codebase (Pydantic, JSON serialization,
    Wazuh/DefectDojo APIs). Centralised so every model uses the same convention.
    """
    return PG_ENUM(
        enum_class,
        name=name,
        create_type=True,
        values_callable=lambda cls: [m.value for m in cls],
    )

# Naming convention so Alembic generates predictable constraint names —
# important for autogenerated migrations that must be stable across machines.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Adds a UUID `id` primary key generated server-side via gen_random_uuid()."""

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """Adds `created_at` and `updated_at` columns, both server-managed."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
